### ISSUE TITLE
curl upload file fail for php 5.6,  {"errcode":41005,"errmsg":"media data missing"} 

### ISSUE THREAD

**Issue by Kengi** [lixuancn/LaneWeChat#14]
php >= 5.5 , 

need CURLFile instead of '@/path/to/file.name'

in core/media.lib.php  line 31:

$data['media'] = class_exists('CURLFile', false) ? new CURLFile($filename) : '@'.$filename;

**Comment by lixuancn** [comment]
文件缺失，你的文件就没传上去

**Comment by hardphp** [comment]
你把问题描述再详细些？

在 2015-06-03 09:05:36，"Lane" <notifications@github.com> 写道：


文件缺失，你的文件就没传上去

**Comment by Kengi** [comment]
是不能上传成功，  我是提醒 有类似 经历的人， 在 php 5.5 以上时，  
 curl 变了  
@/path/to/file.name 这种写法不能工作， 需要改写成 new CURLFile($filename)

**Comment by lixuancn** [comment]
Very Good

**Comment by hardphp** [comment]
<?php
/* http://example.com/upload.php:
<?php var_dump($_FILES); ?>
*/

// Create a cURL handle
$ch = curl_init('http://example.com/upload.php');

// Create a CURLFile object
$cfile = new CURLFile('cats.jpg','image/jpeg','test_name');

// Assign POST data
$data = array('test_file' => $cfile);
curl_setopt($ch, CURLOPT_POST,1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);

// Execute the handle
curl_exec($ch);
?>

**Comment by lixuancn** [comment]
1.5.3中修复。thinks
