### ISSUE TITLE
主动发客服消息模块（responseinitiative.lib.php)好像有小问题！

### ISSUE THREAD

**Issue by zhangshuren** [lixuancn/LaneWeChat#15]
你好，在主动发消息模块（responseinitiative.lib.php）好像有点小瑕疵！
1、发送图文消息函数中pic_url 和 url赋值搞反了，第159行和第160行
2、jsonencode编码时对中文的支持

**Comment by lixuancn** [comment]
问题一：已修复。
问题二：未处理。因为json_encode的JSON_UNESCAPED_UNICODE在5.4以上才有，而大多数的环境目前都是5.3
