### ISSUE TITLE
支持PHP5.2 的LaneWeChat版本

### ISSUE THREAD

**Issue by dongnanyanhai** [lixuancn/LaneWeChat#16]
基于官方1.5.1，除依照官方说明外，还需要：
定义__DIR__常量（该常量是php5.3开始增加的）；
修改Autoloader类中的autoload方法；
注释WechatRequest类中的test方法（应该该方法使用了命名空间Aes\WXBizMsgCrypt）；

下载地址：
链接：http://pan.baidu.com/s/1hqrjQGc 密码：cq0b

**Comment by lixuancn** [comment]
已开分支php5.2。请贡献你的代码。谢谢！

**Comment by dongnanyanhai** [comment]
已经Fork一个，没办法直接提交到5.2分支！

https://github.com/dongnanyanhai/LaneWeChat

**Comment by lixuancn** [comment]
肯定不能直接提交。要Pull Request。你在Fork后在5.2分支下进行你自己的操作（commit，push）。然后PR即可。

复制的  -  什么是Pull Request：
    有一个仓库，叫Repo A。你如果要往里贡献代码，首先要Fork这个Repo，于是在你的Github账号下有了一个Repo A2,。然后你在这个A2下工作，Commit，push等。然后你希望原始仓库Repo A合并你的工作，你可以在Github上发起一个Pull Request，意思是请求Repo A的所有者从你的A2合并分支。如果被审核通过并正式合并，这样你就为项目A做贡献了

如何在Github上为一个项目Pull Request
http://blog.csdn.net/ygrx/article/details/9109783

**Comment by dongnanyanhai** [comment]
已经提交了，你看看是不是这样！
