### ISSUE TITLE
主动存贮access-token问题

### ISSUE THREAD

**Issue by lgshuo** [lixuancn/LaneWeChat#18]
accesstoken.lib.php
第44行  
//存入数据库
        /**
         * 这里通常我会把access_token存起来，然后用的时候读取，判断是否过期，如果过期就重新调用此方法获取，存取操作请自行完成
         *
         * 请将变量$accessTokenJson给存起来，这个变量是一个字符串
         */
        $f = fopen('access_token', 'w+');
        fwrite($f, $accessTokenJson);
        fclose($f);
        return $accessToken;
 这里已经储存了 access-token啊

**Comment by lixuancn** [comment]
sae不能用fwrite自己写文件。有人要存数据库。这只是一个实例。
