### ISSUE TITLE
你好 十分感谢分享

### ISSUE THREAD

**Issue by ddbxyrj** [lixuancn/LaneWeChat#21]
感谢您的努力是我们更有效率的开发
问题：
 主动回复（responseinitiative.lib.php）中 36行$template = json_encode($template); 如果是中文是否需要编码转换

**Comment by ddbxyrj** [comment]
比如使用json_encode("中文", JSON_UNESCAPED_UNICODE);

**Comment by lixuancn** [comment]
https://github.com/lixuancn/LaneWeChat/issues/6
