### ISSUE TITLE
php7跑不动的样子

### ISSUE THREAD

**Issue by a395183830** [lixuancn/LaneWeChat#24]
core/wechat.lib.php
HTTP_RAW_POST_DATA  在php7已经被移除了吧

**Comment by lixuancn** [comment]
的确，HTTP_RAW_POST_DATA再5.6就不推荐使用了。
已经修复。
替换为php://input了。

**Comment by IKKIIKKI** [comment]
最近在学习你的一些项目,现在您的主页无法访问,您看看是什么问题,谢谢!

**Comment by lixuancn** [comment]
多谢提醒。SAE改了收费方式。我账户原本还可以用几年的，现在直接欠费了。
