### ISSUE TITLE
openid 怎么获取？？？？？？？

### ISSUE THREAD

**Issue by tyz-coder** [lixuancn/LaneWeChat#31]
openid 怎么获取？？？？？？？
这一句费非要吗？我不跳转就获取不到 openid了？
WeChatOAuth::getCode('/app/index.html', 1, 'snsapi_base');

**Comment by tyzChar** [comment]
如果我只需要一个openid，不进行跳转，为什么没有这个接口呢？后端获取到了数据向前端渲染，数据后端自然会进行处理,存个token意义不大，并且前端只需要一个openid就可以了，其他的事情都交给后端处理就可以了吧？

**Comment by lixuancn** [comment]
网页授权的必须要这么做，这是微信的流程

**Comment by tyz-coder** [comment]
好的，我知道了，真是得在重定向之后获取openid
