### ISSUE TITLE
我发现了一个问题，如果服务器路径区分大小写会出现找不到Class的问题

### ISSUE THREAD

**Issue by tyz-coder** [lixuancn/LaneWeChat#32]
`public static function autoload($className){
        $namespacePrefixStrlen = strlen(self::NAMESPACE_PREFIX);
        if(strncmp(self::NAMESPACE_PREFIX, $className, $namespacePrefixStrlen) === 0){
            $className = strtolower($className);
            $filePath = str_replace('\\', DIRECTORY_SEPARATOR, substr($className, $namespacePrefixStrlen));
            $filePath = realpath(__DIR__ . (empty($filePath) ? '' : DIRECTORY_SEPARATOR) . $filePath . '.lib.php');
            // echo $filePath; //加载类的绝对路径
            if(file_exists($filePath)){
                require_once $filePath;
            }else{
                echo $filePath;
            }
        }
    }`
strtolower($className); 这里把路径变成了小写，是否合理呢？服务器会区分路径的大小写就找不到这个类文件了

**Comment by lixuancn** [comment]
这个autoload仅仅是为了LaneWeChat内部做自动载入的。在LaneWeChat里，他们都是小写的
