### ISSUE TITLE
主动发送消息时 ，中文在wechat中 显示为unicode 码

### ISSUE THREAD

**Issue by Kengi** [lixuancn/LaneWeChat#6]
在CentOS 7.0 php 5.6.5 环境中 

调用 ResponseInitiative::text($openId, $msg) 时 

必须得 改动 lanewechat/core/responseinitiative.lib.php 的 37 行 
`$template = json_encode($template, JSON_UNESCAPED_UNICODE);`

应该很多地方都需要为 json_encode 加上 JSON_UNESCAPED_UNICODE 选项

**Comment by lixuancn** [comment]
JSON_UNESCAPED_UNICODE 只有在php5.4以上才可以。但是绝大多数的环境现在都是5.3及以下。。所以这里只能自行处理喽

**Comment by lixuancn** [comment]
为什么又打开了，还有什么问题吗

**Comment by Kengi** [comment]
Sorry, 我想打开，是误点了哪里吧，  没有问题了， 谢谢
