### ISSUE TITLE
此微信框架是不是仅仅支持单用户？

### ISSUE THREAD

**Issue by JasonPinet** [lixuancn/LaneWeChat#7]
此微信框架是不是仅仅仅仅适用于单用户？如果适用于多用户，我看到获取暂存的access_token这块的处理并不恰当

**Comment by lixuancn** [comment]
在文档和注释那里我著名了一下。暂存的方式要自己来写的。

因为有人要写mysql，有人要写文件，有人要写redis。。。实在不好统一。

比如sae不能写文件 -.-

你有什么好的方式吗？
